# Generated by Django 4.1.3 on 2022-12-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'corpus_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorpusConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=200)),
                ('response', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'corpus_conversation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoChatterbotStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('conversation', models.CharField(max_length=32)),
                ('in_response_to', models.CharField(blank=True, max_length=255, null=True)),
                ('persona', models.CharField(max_length=50)),
                ('search_text', models.CharField(max_length=255)),
                ('search_in_response_to', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'django_chatterbot_statement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoChatterbotStatementTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'django_chatterbot_statement_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoChatterbotTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'django_chatterbot_tag',
                'managed': False,
            },
        ),
    ]
