# Generated by Django 4.1 on 2022-08-07 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('1', 'مرکز اداری'), ('2', 'مرکز درمانی')], max_length=2)),
                ('deleted', models.BooleanField(default=False)),
                ('parent_unit', models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='organization.organizationunit')),
            ],
        ),
    ]
