# Generated by Django 4.1 on 2022-08-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='parent', to='organization.organizationunit'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_type',
            field=models.CharField(choices=[('1', 'مرکز اداری'), ('2', 'مرکز درمانی')], max_length=2, verbose_name='Type of Organization Unit'),
        ),
    ]
