# Generated by Django 4.1 on 2022-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organizationunit_parent_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationunit',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='organizationunit',
            name='unit_name',
            field=models.CharField(max_length=100, verbose_name='Organization or Unit name'),
        ),
    ]
