# Generated by Django 4.1.3 on 2022-11-22 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.CharField(max_length=200, verbose_name='Statement')),
                ('response', models.CharField(max_length=300, verbose_name='Response')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='categories', to='corpus.category')),
            ],
        ),
    ]
