# Generated by Django 4.1 on 2022-08-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='Response',
            new_name='response',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='Statement',
            new_name='statement',
        ),
    ]
