# Generated by Django 4.1.3 on 2022-12-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='train',
            field=models.IntegerField(default=0),
        ),
    ]
