# Generated by Django 4.1 on 2022-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_on',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
