# Generated by Django 4.1 on 2022-08-13 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_password_changedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
