# Generated by Django 4.1 on 2022-08-21 06:17

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organizationunit_deleted_and_more'),
        ('users', '0003_alter_customuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='organization', to='organization.organizationunit'),
        ),
    ]
