# Generated by Django 4.1 on 2022-08-21 07:03

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organizationunit_deleted_and_more'),
        ('users', '0004_customuser_image_avatar_customuser_organization_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image_avatar',
            field=models.ImageField(blank=True, upload_to=users.models.user_directory_path, verbose_name='Profile Image'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(default=None, help_text='Required. Incorrect formatting may result in undelivered messages or a message being sent to an incorrect handset.', max_length=20, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='organization', to='organization.organizationunit', verbose_name='Organization Unit'),
        ),
    ]
