# Generated by Django 4.1 on 2022-08-25 16:13

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(default=None, help_text='Required. Incorrect formatting may result in undelivered messages or a message being sent to an incorrect handset.', max_length=20, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='natinal_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[users.models.national_code_validator], verbose_name='Natinal ID of person'),
        ),
    ]
